version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: brandvx
    env_file:
      - .env.db
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "8000"
    command: uvicorn src.backend.app.main:app --host 0.0.0.0 --port 8000

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - app

volumes:
  dbdata:


