databases:
- name: brandvx-db
  databaseName: brandvx
  user: brandvx
  plan: starter

services:
- type: web
  name: brandvx-app
  env: docker
  plan: starter
  autoDeploy: true
  rootDir: Aube-Coding-Framework
  healthCheckPath: /health
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: brandvx-db
      property: connectionString
  - key: CORS_ORIGINS
    value: https://aubecreativelabs.com
  - key: JWT_SECRET
    generateValue: true
  - key: JWT_AUDIENCE
    value: brandvx-users
  - key: JWT_ISSUER
    value: brandvx
  - key: POSTHOG_API_KEY
    sync: false
  - key: POSTHOG_HOST
    value: https://app.posthog.com
  - key: OPENAI_API_KEY
    sync: false
  - key: REDIS_URL
    sync: false


