databases:
- name: brandvx-db
  databaseName: brandvx
  user: brandvx
  plan: free

services:
- type: web
  name: brandvx-app
  env: docker
  plan: free
  autoDeploy: true
  dockerfilePath: Aube-Coding-Framework/Dockerfile
  healthCheckPath: /health
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: brandvx-db
      property: connectionString
  - key: CORS_ORIGINS
    value: https://aubecreativelabs.com
  - key: JWT_SECRET
    generateValue: true
  - key: JWT_AUDIENCE
    value: brandvx-users
  - key: JWT_ISSUER
    value: brandvx
